### ISSUE TITLE
instance-based events

### ISSUE THREAD

**Issue by fcurella** [robinhood/thorn#7]
It would be useful if subscribers could receive events only related to a specific instance.

Scenario:

A web application lets users create their own `AddressBook`. Each `AddressBook` have many `Contact`s:

```python
class AddressBook(models.Model):
    user = models.ForeignKey('auth.User')

@webhook_model(
    on_create=ModelEvent('contact.created'),
)
class Contact(models.Model):
    name = models.CharField(max_length=255)
    address_book = models.ForeignKey(AddressBook, related_name='contacts')
```

There doesn't seem to be a way for a subscriber to receive `contact.created` events only for `Contact`s of a specific `AddressBook`.

**Comment by fcurella** [comment]
just found about `sender_field`. Closing.

**Comment by ask** [comment]
Yeah, the sender_field should work here when you are mapping to a user, possible that it even works for objects that are not users also.

In my first webhook library written a long time ago, the subscribers could match arbitrary fields on the model: https://github.com/ask/durian
This makes for some pretty expensive queries, but maybe it could be extended in Thorn also.

Maybe the event name could have formats so that (if AddressBook here had a name, and a user can have multiple address books (Work, Friends):

<pre>
@webhook_model(
    on_create=ModelEvent('contact.created.{addressbook.name}'),
    sender_field="address_book.user",
)
</pre>

Then you could subscribe to `contact.created.*`, `contact.created.Friends`, etc.

**Comment by fcurella** [comment]
@ask, I've wrote an initial implementation for instance-based event name formatting in #8
